/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Ground: THREE.Mesh;
    Monitor: THREE.Mesh;
    Keyboard: THREE.Mesh;
    Tree: THREE.Mesh;
    leaf_tree: THREE.Mesh;
    paille_i007: THREE.Mesh;
    paille_i008: THREE.Mesh;
    paille_i009: THREE.Mesh;
    paille_i010: THREE.Mesh;
    paille_i011: THREE.Mesh;
    paille_i012: THREE.Mesh;
    Shimenawa004: THREE.Mesh;
    Shimenawa005: THREE.Mesh;
    Shimenawa006: THREE.Mesh;
    Shimenawa007: THREE.Mesh;
    Shimenawa008: THREE.Mesh;
    Shimenawa009: THREE.Mesh;
    Mouse: THREE.Mesh;
    Torii: THREE.Mesh;
    paille_i001: THREE.Mesh;
    paille_i002: THREE.Mesh;
    paille_i003: THREE.Mesh;
    paille_i004: THREE.Mesh;
    paille_i005: THREE.Mesh;
    paille_i: THREE.Mesh;
    paille_i006: THREE.Mesh;
    Shimenawa: THREE.Mesh;
    Shimenawa001: THREE.Mesh;
    Shimenawa002: THREE.Mesh;
    Shimenawa003: THREE.Mesh;
    Screen: THREE.Mesh;
    rock_i003: THREE.Mesh;
    rock_i005: THREE.Mesh;
    rock_i006: THREE.Mesh;
    rock_i004: THREE.Mesh;
    rock_i008: THREE.Mesh;
    rock_i009: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    rock_i007: THREE.Mesh;
    Circle: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Nuage: THREE.Mesh;
    Nuage001: THREE.Mesh;
    Nuage002: THREE.Mesh;
    Nuage003: THREE.Mesh;
    Nuage004: THREE.Mesh;
  };
  materials: {};
};

export default function MomijiNetwork(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/momiji_network_diorama.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={nodes.Ground.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor.geometry}
        material={nodes.Monitor.material}
        position={[-0.76, 5.09, 2.01]}
        rotation={[-0.32, 0.01, -0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard.geometry}
        material={nodes.Keyboard.material}
        position={[-3.32, 0.73, 8.3]}
        rotation={[2.94, -1.32, 2.82]}
        scale={1.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree.geometry}
        material={nodes.Tree.material}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leaf_tree.geometry}
          material={nodes.leaf_tree.material}
          position={[-0.11, 15.84, -2.63]}
          rotation={[-0.04, 0.33, -0.05]}
          scale={[0.99, 0.83, 1.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i007.geometry}
          material={nodes.paille_i007.material}
          position={[0.46, 1.47, 0.02]}
          rotation={[1.28, 0.28, 0.97]}
          scale={0.21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i008.geometry}
          material={nodes.paille_i008.material}
          position={[-0.35, 1.4, -0.49]}
          rotation={[1.87, -1, 0.69]}
          scale={[0.12, 0.19, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i009.geometry}
          material={nodes.paille_i009.material}
          position={[-1.19, 1.12, -0.64]}
          rotation={[-2.94, -0.58, -2.96]}
          scale={[0.24, 0.2, 0.16]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i010.geometry}
          material={nodes.paille_i010.material}
          position={[-1.71, 0.5, -0.01]}
          rotation={[-0.25, -0.79, -0.33]}
          scale={[0.24, 0.2, 0.16]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i011.geometry}
          material={nodes.paille_i011.material}
          position={[0.4, 0.93, 0.99]}
          rotation={[2.8, 0.28, -2.97]}
          scale={0.14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i012.geometry}
          material={nodes.paille_i012.material}
          position={[-0.07, 0.34, 1.84]}
          rotation={[-3.07, 0.11, 3.05]}
          scale={0.14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa004.geometry}
          material={nodes.Shimenawa004.material}
          position={[-0.08, 1.45, -0.18]}
          rotation={[-3.09, 0.19, -3.08]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa005.geometry}
          material={nodes.Shimenawa005.material}
          position={[-0.75, 1.4, -0.61]}
          rotation={[2.3, 0.57, -2.79]}
          scale={0.45}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa006.geometry}
          material={nodes.Shimenawa006.material}
          position={[-1.42, 1.05, -0.37]}
          rotation={[-1.83, -0.07, 1.4]}
          scale={0.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa007.geometry}
          material={nodes.Shimenawa007.material}
          position={[-1.88, 0.35, 0.39]}
          rotation={[1.45, 0.08, 1.67]}
          scale={[-0.36, -0.2, -0.48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa008.geometry}
          material={nodes.Shimenawa008.material}
          position={[0.58, 1.18, 0.65]}
          rotation={[1.17, -0.02, -2.29]}
          scale={[0.38, 0.45, 0.54]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa009.geometry}
          material={nodes.Shimenawa009.material}
          position={[0.26, 0.76, 1.43]}
          rotation={[1.18, 0.23, -1.19]}
          scale={[0.38, 0.45, 0.54]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={nodes.Mouse.material}
        position={[5.27, 1.08, 6.74]}
        rotation={[0, 0.44, 0]}
        scale={0.79}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torii.geometry}
        material={nodes.Torii.material}
        position={[0, 0, -7.02]}
        scale={2.65}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i001.geometry}
          material={nodes.paille_i001.material}
          position={[-0.51, 2.14, -0.16]}
          rotation={[0.1, -0.72, -0.02]}
          scale={[0.12, 0.15, 0.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i002.geometry}
          material={nodes.paille_i002.material}
          position={[0.49, 2.18, -0.02]}
          rotation={[-0.16, -0.01, 0.02]}
          scale={[0.12, 0.14, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i003.geometry}
          material={nodes.paille_i003.material}
          position={[0.94, 2.38, -0.18]}
          rotation={[-2.94, -0.07, 2.95]}
          scale={0.15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i004.geometry}
          material={nodes.paille_i004.material}
          position={[-0.89, 2.38, -0.18]}
          rotation={[0.13, -0.04, -0.02]}
          scale={[0.15, 0.15, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i005.geometry}
          material={nodes.paille_i005.material}
          position={[-1.03, 2.56, 0.05]}
          rotation={[0.32, -1.09, -0.02]}
          scale={[0.14, 0.13, 0.09]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i.geometry}
          material={nodes.paille_i.material}
          position={[1.06, 2.53, 0.09]}
          rotation={[0.55, -1.25, 0.58]}
          scale={0.15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paille_i006.geometry}
          material={nodes.paille_i006.material}
          position={[0, 2, -0.07]}
          rotation={[Math.PI, -0.26, Math.PI]}
          scale={0.15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa.geometry}
          material={nodes.Shimenawa.material}
          position={[-0.28, 2.21, -0.08]}
          rotation={[1.59, -0.28, -2.93]}
          scale={0.35}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa001.geometry}
          material={nodes.Shimenawa001.material}
          position={[0.27, 2.21, -0.08]}
          rotation={[1.61, -0.1, -2.72]}
          scale={[0.28, 0.34, 0.35]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa002.geometry}
          material={nodes.Shimenawa002.material}
          position={[0.72, 2.4, -0.1]}
          rotation={[1.61, -0.22, -2.72]}
          scale={[0.35, 0.35, 0.26]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shimenawa003.geometry}
          material={nodes.Shimenawa003.material}
          position={[-0.73, 2.37, -0.1]}
          rotation={[1.61, -0.25, -2.72]}
          scale={0.33}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={nodes.Screen.material}
        position={[-0.76, 5.09, 2.01]}
        rotation={[-0.32, 0.01, -0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i003.geometry}
        material={nodes.rock_i003.material}
        position={[8.15, 0.15, 3.66]}
        rotation={[-0.99, -1.49, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i005.geometry}
        material={nodes.rock_i005.material}
        position={[0.95, -0.42, -7.66]}
        rotation={[0.07, -0.66, 1.14]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i006.geometry}
        material={nodes.rock_i006.material}
        position={[-1.73, -0.5, -8.89]}
        rotation={[0.2, -0.22, -2.69]}
        scale={0.72}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i004.geometry}
        material={nodes.rock_i004.material}
        position={[2.41, 0.51, -2.91]}
        rotation={[2.65, 0.34, 1.97]}
        scale={1.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i008.geometry}
        material={nodes.rock_i008.material}
        position={[-1.66, 0.18, -7.8]}
        rotation={[2.16, -0.66, -0.56]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i009.geometry}
        material={nodes.rock_i009.material}
        position={[-9.03, 0.22, -1.67]}
        rotation={[1.23, -0.87, 2.42]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, -1.36, -8.35]}
        scale={[0.78, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0, -0.84, -7.32]}
        scale={[1.31, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0, -0.32, -6.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_i007.geometry}
        material={nodes.rock_i007.material}
        position={[1.44, -0.52, -8.27]}
        rotation={[1.88, -0.33, 2.6]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[0.7, 0, 7.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-6.6, -0.15, 6.57]}
        rotation={[-2.77, 0.87, 2.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-3.83, 0.04, -9.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[3.86, 0.04, -9.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nuage.geometry}
        material={nodes.Nuage.material}
        position={[-9.07, 2.11, -4.09]}
        scale={1.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nuage001.geometry}
        material={nodes.Nuage001.material}
        position={[9.64, 7.09, 2.59]}
        rotation={[0, 0, -Math.PI]}
        scale={[2.23, 2.56, 1.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nuage002.geometry}
        material={nodes.Nuage002.material}
        position={[-5.27, 14.17, 6.36]}
        scale={[4.01, 1.88, 1.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nuage003.geometry}
        material={nodes.Nuage003.material}
        position={[-8.08, 7.1, -13.74]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.95, 2.89, 4.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nuage004.geometry}
        material={nodes.Nuage004.material}
        position={[-128.87, 37.38, -64.98]}
        rotation={[-2.68, -1.06, -2.74]}
        scale={[32.8, 22.9, 36.88]}
      />
    </group>
  );
}

useGLTF.preload("/momiji_network_diorama.glb");
